#' Load cached model output for a mutation and parameter setting
#'
#' Retrieves a cached model output object from disk using a standardized
#' cache filename generated by \code{cache_path()}. The function assumes
#' that the cached file already exists and will error if it does not.
#'
#' This helper is intended for workflows where model fitting has already
#' been completed and results are reused for downstream analysis or plotting.
#'
#' @param mut Character string specifying the mutation identifier used
#'   to construct the cache filename.
#'
#' @details
#' The cache file path is generated via \code{cache_path()}, using a fixed
#' cache key (\code{"optimized_ell_tau2_full_model_output"}) and the
#' \code{"rds"} extension.
#'
#' If the cache file does not exist, the function stops with an error.
#' No model fitting or recomputation is performed.
#'
#' @return
#' An R object loaded from the cached \code{.rds} file (typically a list
#' containing model outputs such as posterior summaries, grids, and
#' metadata).
#'
#' @examples
#' \dontrun{
#' model_out <- make_or_load(
#'   mut   = "k13:561:H",
#'   ell_km = 120,
#'   tau2   = 0.5
#' )
#'
#' names(model_out)
#' }
#'
#' @importFrom fs file_exists
#'
#' @export
make_or_load <- function(mut) {
  cached_rds <- cache_path(
    mut = mut, 
    what = "optimized_ell_tau2_full_model_output", 
    ext = "rds"
  )
  stopifnot(file_exists(cached_rds))
  readRDS(cached_rds)
}
